[package]
name = "omniartis-demo"
version = "0.0.1-pre.0.1.0"
edition = "2021"
description = "A demo for my game, Omniartis (https://queenkirathepansexualpixie.github.io/devlogs/projects/omniartis.html)"

[dependencies]
bevy = "0.14.2"
